# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pantry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the ingredient name (e.g. Salt or Onion)', max_length=100)),
                ('category', models.CharField(default='None', help_text='Enter the ingredient category (e.g. Spice or Meat)', max_length=100)),
            ],
        ),
    ]
