# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pantry', '0002_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipe_id', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=350)),
            ],
        ),
    ]
