# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 22:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pantry', '0003_minirecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myingredient_ing', to='Pantry.Ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myingredient_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
