# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pantry', '0004_myingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='myingredient',
            name='measurement',
            field=models.CharField(default='cups', max_length=20),
        ),
    ]
